### ISSUE TITLE
New Heroku App Control

### ISSUE THREAD

**Issue by adisubagja** [adekmaulana/ProjectBish#14]
Can you add new module for heroku control any other apps from heroku with appname & apikey ?
I mean on off scale,restart,etc dynos other apps heroku using userbot

Sorry bang gabisa basa engres

**Comment by gudmeong** [comment]
> Can you add new module for heroku control any other apps from heroku with appname & apikey ?
> I mean on off scale,restart,etc dynos other apps heroku using userbot
> 
> Sorry bang gabisa basa engres

pake yg fallback

**Comment by adisubagja** [comment]
Sip makasih bang
